name: Handle File Upload

on:
  repository_dispatch:
    types: [updateData]

jobs:
  uploadFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload file
        run: |
          FILE_NAME="${{ github.event.client_payload.filename }}"
          CONTENT="$(echo "${{ github.event.client_payload.data }}" | base64 -d)"
          echo "$CONTENT" > "$FILE_NAME"

      - name: Commit changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add "$FILE_NAME"
          git commit -m "Uploaded file: $FILE_NAME"
          git push
